### ISSUE TITLE
External style configuration file

### ISSUE THREAD

**Issue by AlecsFerra** [phuhl/linux_notification_center#100]
It would be cool to have an option to load an external file for configuring the colors so the application can be themed automatically by software like pywal.

**Comment by Mesabloo** [comment]
After taking a look into [the library I think is used⁽¹⁾](https://hackage.haskell.org/package/ConfigFile-1.1.4/docs/Data-ConfigFile.html), there doesn't seem to be a way of handling file inclusions in configuration files using the library.
We could instead have a key "include" or "import" in the configuration, and handle all the inclusion logic directly in this program⁽²⁾, but this is a little bit more work. (especially considering all the difficulties that could arise)

I unfortunately cannot work on this because I'm on NixOS and there is a [known bug](https://github.com/NixOS/nixpkgs/issues/49206) I ran into that prevents me from compiling the `haskell-gi` package, which is needed by this program.

-------------

**⁽¹⁾**: https://github.com/phuhl/linux_notification_center/blob/a155a6b826b6380f9c712aa07e345a66d0b622a1/linux-notification-center.cabal#L55
**⁽²⁾**: so for example, we could have a configuration file `deadd.conf` containing 
```ini
[colors]
include = "~/.config/deadd/colors.conf"
# other configuration options
```
and the file `colors.conf` with all your colors.
The only problem that seems to arise (as little as I thought about it) is that the `include` key should be somehow replaced in-place (so the included file should take take the place of the `include` option to preserve option ordering, which is vital in an INI-style configuration style with sections). I believe this could mess with a little bit of the current code, unless we provide a way to concatenate two configurations in [`Config.hs`](https://github.com/phuhl/linux_notification_center/blob/master/src/Config.hs), but then we would not preserve key ordering, unless we only allow `include`ing in the `DEFAULT` section (which restricts greatly its use with pieces of software like pywal because it doesn't insert a `[colors]` section header at the top of the file).

**Comment by phuhl** [comment]
This could be a part of a potential restructuring of the config as tracked by #80

**Comment by phuhl** [comment]
I currently don't think, there will be a way to import colors or anything, but you could easily write a script, that patches the new `deadd.css` file (more infos on that here: https://github.com/phuhl/linux_notification_center#css-styling) and than reload the styling information on the fly (more infos on that here: https://github.com/phuhl/linux_notification_center#usage). I guess, that would allow for styling with pywal.

I will close this for now, if I am wrong, and there are further changes needed, feel free to reopen
