### ISSUE TITLE
Readme should provide default deadd.css

### ISSUE THREAD

**Issue by MyriaCore** [phuhl/linux_notification_center#127]
I've actually been having quite a bit of trouble moving my old colors to the new 2021 version. I had a specific opacity setup, and my lack of knowledge about how gtk works is kinda hampering that. 

If I could see the deadd.css that was used to capture the screenshots, that would be *incredibly* helpful.

**Comment by S-NA** [comment]
I am not sure how similar it is to the deadd.css used in the screenshot but the default deadd.css can be found here: https://github.com/phuhl/linux_notification_center/blob/master/style.css

That is if the Makefile is to be trusted.
https://github.com/phuhl/linux_notification_center/blob/62c8e42d3cd8e913320d20a5c18d17725d2ec72d/Makefile#L70-L78

For what it is worth, I had no opacity until I used the contents in style.css in my own local deadd.css.

**Comment by MyriaCore** [comment]
Funny, when I installed via the git version in the AUR, I never got a style.css. Maybe it detected my deadd folder already existed and didn't try to touch it? 

As I've been working w/ the colors, I've still been struggling w/ the CSS a bit though. I'd be surprised of the provided style.css is actually used, I thought it's compiled into the binary as a guide for what the styles should look like by default. Not sure that they match the screenshots as well, since those would probably have been customized by @phuhl to work with his dotfiles.

**Comment by MyriaCore** [comment]
ATM I've personally settled on:

```css
window {
  background-color: rgba(0, 0, 0, 0.5);
}

label.deadd-noti-center.date {
  font-size: 20px;
}

label.deadd-noti-center.noti-center.time {
  font-size: 64px;
}
```

I've been trying to see if I can make it integrate with my pre-existing system style, but things like `alpha(@bg-color, 0.5)` *really* haven't worked well for me. I'll just deal w/ this for now. I do still think a sample like this should be included in the readme, though.

**Comment by phuhl** [comment]
Sorry, prob. should have wrote it more clearly. @S-NA Is correct, the style.css *should* have been copied into your config-folder as long as the file does not exist. Otherwise, there *should* have been the warning as seen in the snipped above.

No css is compiled into the source anymore. The style.css can be used as the template for the screenshots (might vary, but basically it's the same). Probably should have explained that in [updateyourconfig2021.org](https://github.com/phuhl/linux_notification_center/blob/777711e98e956b9afcea0ab6a185ed852cef772f/updateyourconfig2021.org).

I stronly suggest (especially for CSS-novices) to use the style.css as a foundation and change the colors in there. All the colors that were previously defined in the config file are used in the style.css. The actual [commit](https://github.com/phuhl/linux_notification_center/commit/e98058c318773983b5a6992a835dda3dd7680d25#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7a) reveals how the config-options relate to the style.css

**Comment by phuhl** [comment]
Added a note to the README and updateyourconfig2021.org
