### ISSUE TITLE
Changes to deadd.conf should apply to running instance

### ISSUE THREAD

**Issue by wulftone** [phuhl/linux_notification_center#13]
Whenever I make changes to `~/.config/deadd/deadd.conf`, they don't reflect in the running instance of the notification center... I have to restart it.. I would expect to be able to send it a signal to reload the config at the least, or have it detect the config file has changed in some manner.  Restarting it also only changes the "panel" styling, not the notification bubble styling.  I have to logout/login for that to change.  Is there something I'm missing?

**Comment by phuhl** [comment]
> Restarting it also only changes the "panel" styling, not the notification bubble styling. I have to logout/login for that to change. Is there something I'm missing?

I guess, you did not kill it? You have to kill the running instance, otherwise the notifications will be displayed by the first instance you launched. The notification-center itself would only change, because it overlays the other instance and you do not see the old one.
Try `killall deadd-notification-center`.
Regarding automatic reloading of the configuration: I will not implement that. The cost-benefit ratio is too small for me. But feel free to send me a PR if you'd like. Thanks for reporting.
