### ISSUE TITLE
Error whet try to start Deadd Notification Center

### ISSUE THREAD

**Issue by AndresD172** [phuhl/linux_notification_center#187]
Hello! I instaled Deadd Notification Center using `make` and `sudo make install`, and the install elapsed without problems. But at the moment to run deadd-notification-center in console i got the following problem

`deadd-notification-center: symbol lookup error: deadd-notification-center: undefined symbol: pango_layout_deserialize_error_get_type
`
How I can solve the problem? I added a screenshot of the error showed in console.

Greetings! <3

![2022-02-11-094249_1064x36_scrot](https://user-images.githubusercontent.com/57467120/153622259-9826ae81-16ad-461d-addb-a60f45ee2611.png)

**Comment by AndresD172** [comment]
Hello! It's me again. 

I finally solved the problem! I removed the installation created with the make-make install method and reinstalled it with the method described for distributions like Ubuntu, Debian, etc.

But I have two small problems again. I have already started the notification daemon using the `ddead-notification-center` command and in theory it works now, but if a notification arrives the daemon does not show its notification instead of the default notification. And the other problem is that I don`t know how to open the notification center using polybar, I have tried to open it with rofi and with commands in cmd but nothing works. Can anyone help me to solve at least the first problem.... thanks to everyone who can help me!

**Comment by phuhl** [comment]
Hi @AndresD172, can you confirm e.g. by using htop, that ddead-notification-center is actually running?

**Comment by d3adb5** [comment]
The first problem seems to me like a linking problem. With regards to the "default notification" being shown instead of a popup on deadd-notification-center: do you know what your default notification daemon is, @AndresD172? And if so, can you kill its process and see if notifications are handled by deadd?

Since both are likely connecting to DBus and waiting for notifications, I think the first one to have gotten there gets precedence. I'm no DBus expert, but I assume that is what is going on, as if I run Dunst and deadd, only one actually shows any notifications.
