### ISSUE TITLE
Es könnten Daten auf die Festplatte geschrieben werden...

### ISSUE THREAD

**Issue by EyeDevelop** [phuhl/linux_notification_center#19]
## Issue
When I play a certain song this message shows up in German (see title). My system locale is en_GB.UTF-8. The title of the song played is smaller than other songs. The author string is also smaller.

What is happening and what data is it trying to write/written to the harddisk?

**Package**: deadd-notification-center-bin from AUR
**Version**: 1.6.1-1
**OS**: Arch Linux (5.4.3-zen1-1-zen)
**Hardware**: ThinkPad T490

## Steps to reproduce
1. Open Spotify
1. Navigate to the Zelda & Chill playlist by Mikel, GameChops
1. Play the song "Minuet of Forest"

**Comment by paperbenni** [comment]
Same issue here

**Comment by ForsakenHarmony** [comment]
https://github.com/phuhl/linux_notification_center/blob/bc5de6937b63c55267f85b4a589fa2af218eec69/notification.glade#L85

I have no idea what exactly this is for
Seems like it might be an example for long text :thinking:

**Comment by phuhl** [comment]
Hey, I have no idea how that text got in there, but no data was written to your HD due to this. I fixed the issue. It always happend when an `&` was in the notification text, because for the markup of notifications I use the GTK-Markup (https://developer.gnome.org/pango/stable/pango-Markup.html) which does not like single `&`. Now, all `&` are transcribed to `&amp;` which displays them properly. Thank you for reporting :) An update with the fix will follow shortly
