### ISSUE TITLE
Scrippting match patterns

### ISSUE THREAD

**Issue by kristianvld** [phuhl/linux_notification_center#192]
It would be really nice to be able to match patterns and not only exact values.

For instance, being able to match any notifications with a word in the title or body would be nice. Either with simple pattern like
```
match = "title=*black*" # match any title containing the word black
...
match = "title=*black" # match any title ending in the word black
...
match = "title=/[0-9a-f]{16} black/i" # regex, match titles starting with a 16 digit hex number and ending in black, ignore case
...
match = "title=*" # matches all notifications
```

This on it's own could be really powerful, but even more so when #138 gets implemented.

The last example would also be a nice way to match any notifications. Currently I don't see any way to do this, even though I would expect an empty match to do this (as all [none] match conditions are met).

**Comment by phuhl** [comment]
Not entirely sure, but I think in https://github.com/phuhl/linux_notification_center/pull/138 you can match everything by having an empty match.

Then you could use the scripting method to match however you like in a script and only modify when you match, using this:
![image](https://user-images.githubusercontent.com/16835755/169089460-46407507-e1fa-46eb-ba69-82d74fda8674.png)

Btw, you can test what is in https://github.com/phuhl/linux_notification_center/pull/138 as of today. The code is there. The only reason it is not merged, yet, is because it has a lot of braking changes regarding configuration. But one day, when I feel brave, I probably will merge.

**Comment by phuhl** [comment]
Should be fixed by new config format

**Comment by TIAcode** [comment]
I don't think matching all works?
Without any match:
`deadd-notification-center: AesonException "Error in $.modifications[7]: key \"match\" not found"`
Empty match block"
`deadd-notification-center: AesonException "Error in $.modifications[7].match: parsing Map failed, expected Object, but encountered Null"`
And matching with an empty filter string doesn't match anything.

**Comment by phuhl** [comment]
What is your config?

**Comment by TIAcode** [comment]
All right, apparently I didn't know how to define empty Maps in yaml, your question made me question my own knowledge and I found a solution. If anyone else is looking for it
```
  modifications:
    - match: {}
      script: "/home/santzes/.config/qtile/notifications/processor/process_notification.py"
```
seems to match everything. Thanks
