### ISSUE TITLE
Notification area in the Center is too small, when one of the messages is too long

### ISSUE THREAD

**Issue by dmigis** [phuhl/linux_notification_center#40]
There is a problem: The area in which notifications are displayed is arbitrarily clipped, if there at least one of the notifications is too long. Using deadd-notification-center-bin from AUR. Same with deadd-notification-center

**Comment by MyriaCore** [comment]
I experienced this when implementing #78. I believe @phuhl did too.

**Comment by phuhl** [comment]
it is a little annoying to deal with because it is a fight against gtk but it is an annoying bug, too.

**Comment by MyriaCore** [comment]
See: https://github.com/phuhl/linux_notification_center/pull/78#issuecomment-683624835

**Comment by MyriaCore** [comment]
This bug appears quite frequently for me in the master branch of my fork. Not rly sure when I'll have any time to implement a fix, but I'd love any insight on how to fix this

**Comment by MyriaCore** [comment]
Looking into things more, it seems like this dLabelBG thing is a dummy label that's only used to size itself up so the size can propogate to the parent. I'm almost certain there's a better way to do this lol

**Comment by phuhl** [comment]
Afaik you can only set the height, but not the width with GTK. Why I used the label, I don't know anymore, but surely there was a reason

**Comment by MyriaCore** [comment]
I don't doubt that you had your reasons, it just feels like [`widgetSetSizeRequest`](https://www.stackage.org/haddock/lts-16.13/gi-gtk-3.0.33/GI-Gtk-Objects-Widget.html#v:widgetSetSizeRequest) should still be able to set width. I mean, the docs *say* it does. Maybe you ran into a bug when doing that? 

Even so, this code shouldn't rly be running for the notification center, right? Like the code in `NotificationPopup` is only for popups I thought. In fact, wouldn't [`NotificationInCenter.showNotification`](https://github.com/phuhl/linux_notification_center/blob/499c75b04ab1c06239d9d516c7354d5a96c8d4da/src/NotificationCenter/NotificationInCenter.hs#L54-L100) be called instead, via [`NotificationCenter.updateNotis`](https://github.com/phuhl/linux_notification_center/blob/499c75b04ab1c06239d9d516c7354d5a96c8d4da/src/NotificationCenter.hs#L327)?

I'm sure this was the source of the button bug (which would ideally be fixed in #77), but maybe the source of this bug is something else?

**Comment by phuhl** [comment]
Yeah, that particular label should not play any role in this. The notifications in center don't even have that lable iirc...
