### ISSUE TITLE
Disable Notifications

### ISSUE THREAD

**Issue by Ayush1325** [phuhl/linux_notification_center#48]
Is there a way to stop notification pop-ups for a while, like DND? So during that time no pop-up shows but the notifications are present in the notification center.

Dunst seems to do it using 
`killall -SIGUSR1 dunst`
or
`notify-send "DUNST_COMMAND_PAUSE"`

**Comment by MyriaCore** [comment]
This is a useful feature for sure. It'd be an enhancement over dunst as well, since ideally the notification center would still *record* notifications when you check, but just won't push anything to the screen or play any audio.

**Comment by koenmetsu** [comment]
Still recording them would be nice, but I'd be very happy with just receiving no notifications as a first implementation, for during video calls or presentations.

**Comment by MyriaCore** [comment]
I just forged this repo, so hopefully I'll be able to figure this thing out and make a PR here. I'm unfortunately not a haskell programmer, but this project has given me an excuse to try it out.

We could try to add a notification center hint command. This is how clearing notifications in the notification center through an external script is currently handled:

```sh
# within the notification center
notify-send.py a --hint boolean:deadd-notification-center:true \
               string:type:clearInCenter
```

The code that parses these commands is [here](https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/NotificationCenter.hs#L251-L259):

https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/NotificationCenter.hs#L251-L259

Currently `hideAllNotis` is used to clear popups. It could just be named weirdly, since it *sounds* like what we want, but my theory is that if we try to use *this* function, we'll get the wrong behavior (like, notifications would popup and get immediatley cleared or something like that). 

I think to get the control flow working, we'd have to set some kind of state variable upon receiving the pause notifications command, and then in the [update function](
https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/NotificationCenter.hs#L303-L335), we'll have to add a guard that reads this variable before adding any new notifications to the list:

https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/NotificationCenter.hs#L326-L329

This way, we can run `hideAllNotis` to clear any popups that *currently* exist, then set this variable, so whenever any *new* notifications come in, they won't be rendered. 

The big worry with this setup is how to ensure the notifications will be saved. As far as I can tell, [this](https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/NotificationCenter.hs#L316-L320) bit of code *should* be responsible for showing the notification *in the notification center*: 

https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/NotificationCenter.hs#L316-L320

If this is the case, then nothing fancy needs to be done - this should still be able to run unconditionally, and we should be fine. 

I'm not 100% sure if this setup will work, but I *think* it should. I'll see if I can draft something up over at [`Myriacore:disable-notifs`](https://github.com/MyriaCore/linux_notification_center/tree/disable-notifs).

**Comment by MyriaCore** [comment]
Here are the current ways to pause / unpause popups in my fork. Do you think I should add one for toggling, or is this functionality good? 

```sh
# within the notification center
notify-send.py a --hint boolean:deadd-notification-center:true \
               string:type:pausePopups

# within the notification center
notify-send.py a --hint boolean:deadd-notification-center:true \
               string:type:unpausePopups
```
