### ISSUE TITLE
Modify Icon

### ISSUE THREAD

**Issue by MyriaCore** [phuhl/linux_notification_center#68]
The [readme](https://github.com/phuhl/linux_notification_center#notification-based-scripting) notes that trying to modify the app icon doesn't currently do anything. That is indeed the case. 

Is this planned, currently? I couldn't find it in the ['log of issues'](https://github.com/phuhl/linux_notification_center/blob/master/Worklog.org), which I assume is meant to be a roadmap.

**Comment by MyriaCore** [comment]
I'm a bit more comfortable with the codebase than I was 16 days ago, so I did some sleuthing. Here's where the match / modify rules get parsed: 

https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/src/Config.hs#L170-L179

Line 175, the line with the modify rule for icons, is commented out. A quick [blame](https://github.com/phuhl/linux_notification_center/blame/69b160676064418dd08ebc6b65763f31a649f061/src/Config.hs#L175) reveals that it was commented out in 37e4ae6

A [blame on the README](https://github.com/phuhl/linux_notification_center/blame/69b160676064418dd08ebc6b65763f31a649f061/README.org#L506) reveals that this line was written way earlier, implying that after 2 years of no working implementation, this feature was likely given up on.

@phuhl Why didn't just re-packing with `v` work? AFAICT, `icon` should just be a gtk icon name, right?

**Comment by phuhl** [comment]
Hey, @MyriaCore 

The issue is (if I remember correctly), that the icon (as specified by the gnome desktop notification protocol) can be send in three different ways. It can eather be a gtk icon name, or a path to an icon, or raw image data.

In order to implement icons in the first place, I cut this feature. Currently I am too busy otherwise to work actively on this (as can be seen by my late answers, sorry about that). Should you want to try and implement this feature, I can give you some pointers, where to look in the codebase, and so on.

**Comment by MyriaCore** [comment]
That makes sense. Even so, we could still restrict modify to only one format, which would reduce implementation complexity, right? Like, if we only allowed the user to modify with a valid gtk icon name.

**Comment by phuhl** [comment]
I think, if we felt like it, both, by path and by GTK icon name would be rather doable and sensible.

But only supporting the one is definitively the easiest way to do it for now!
