### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by AFAgarap** [phuhl/linux_notification_center#73]
Hello, may I ask how can I uninstall this notification center? Thank you.

**Comment by MyriaCore** [comment]
I guess depends on how you installed? My `make install` gives me this:

<details>
<summary><code>make install</code> output</summary>

```
mkdir -p /usr/bin
install -m755 .out/deadd-notification-center /usr/bin
mkdir -p /usr/share/man/man1
install -m644 docs/linux-notification-center.man /usr/share/man/man1/deadd-notification-center.1
install -Dm644 LICENSE /usr/share/licenses/deadd-notification-center/LICENSE
mkdir -p /usr/lib/systemd/user
install -m644 deadd-notification-center.service /usr/lib/systemd/user
mkdir -p /usr/share/dbus-1/services
install -m644 com.ph-uhl.deadd.notification.service /usr/share/dbus-1/services
mkdir -p /usr/share/locale/de/LC_MESSAGES
mkdir -p /usr/share/locale/en/LC_MESSAGES
install -m644 translation/de/LC_MESSAGES/deadd-notification-center.mo /usr/share/locale/de/LC_MESSAGES/deadd-notification-center.mo
install -m644 translation/en/LC_MESSAGES/deadd-notification-center.mo /usr/share/locale/en/LC_MESSAGES/deadd-notification-center.mo
```
</details>

So I assuming you installed by doing that, your steps are probably something like:

1. `rm /usr/bin/deadd-notification-center`
2. `rm /usr/share/man/man1/deadd-notification-center.1`
3. `rm -rf /usr/share/licenses/deadd-notification-center`
4. `rm /usr/lib/systemd/user/deadd-notification-center.service`
5. `rm /usr/share/dbus-1/services/com.ph-uhl.deadd.notification.service`
6. `rm /usr/share/locale/de/LC_MESSAGES/deadd-notification-center.mo`
7. `rm  /usr/share/locale/en/LC_MESSAGES/deadd-notification-center.mo`
8. If you want to remove your settings too: `rm -rf ~/.config/deadd`

If you installed via your package manager, you can probably just uninstall through that. Although, I'm sure you didn't, since you probably wouldn't be asking this question if that were the case.

**Comment by MyriaCore** [comment]
NVM, it appears there's a [`make uninstall` command](https://github.com/phuhl/linux_notification_center/blob/69b160676064418dd08ebc6b65763f31a649f061/Makefile#L88-L93)

Instead of doing what I said, I suggest you try using this, by just typing `sudo make uninstall` into your command prompt.

**Comment by AFAgarap** [comment]
Thank you!
