### ISSUE TITLE
Update Stack.yaml and Cabal Files

### ISSUE THREAD

**Issue by mitchell-gil96** [phuhl/linux_notification_center#85]
The lastest stack and cabal files are from 6 months ago and were generated from the 1.6.0 build.

The gi-pango 1.0.22 from that build has a bug where it parses harfbuzz incorrectly as reported here
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968729
and got fixed in gi-pango 1.0.23

The gi-pango bug is also reported here:
https://aur.archlinux.org/packages/deadd-notification-center/

My best guess is that current 1.7.2 was built on a different stack LTS GHC than the latest stack.yaml and .cabal files posted in the repo.

```
gi-pango                 > [85 of 94] Compiling GI.Pango.Objects.Font
gi-pango                 >
gi-pango                 > /tmp/stack-69059c6a2ea7a9dc/gi-pango-1.0.22/GI/Pango/Objects/Font.hs:669:9: error:
gi-pango                 >     parse error on input ‘HarfBuzz.FeatureT.feature_t’
gi-pango                 >     |
gi-pango                 > 669 |     Ptr HarfBuzz.FeatureT.feature_t ->      -- features : TCArray False (-1) 2 (TInterface (Name {namespace = "HarfBuzz", name = "feature_t"}))
gi-pango                 >     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi-pango                 >

```

**Comment by MyriaCore** [comment]
Is this seperate from #45, or is it the same?

**Comment by MyriaCore** [comment]
This is gonna be a hell of a project lol. 

Tried nuking the stack files and initializing them with a new resolver:

```
Selected resolver: lts-16.7
Resolver 'lts-16.7' does not have all the packages to match your requirements.
    cairo not found
        - linux-notification-center requires -any
    dbus version 1.2.16 found
        - linux-notification-center requires >=0.10.15 && <1
    gtk3 not found
        - linux-notification-center requires >=0.15.4
    hgettext not found
        - linux-notification-center requires >=0.1.5
    system-locale not found
        - linux-notification-center requires -any
``` 

It seems basically all of these packages aren't on stackage. Not sure if it's possible to just get stack to use hackage instead. Do you remember renaming / deleting any deps? My theory is that, for example, maybe `cairo` just merged into `gi-cairo` or something.

**Comment by mitchell-gil96** [comment]
I believe its the cause of #45, same issue just with better context.

As far as the "project" goes, it seems that these files can be auto-generated by whoever wrote the code itself. If im not mistaken, its as simple as running one or two commands from an IDE. Both files in question state in their first lines that they were auto-generated and to not manually alter them.

**Comment by mitchell-gil96** [comment]
I have a hunch that at some point between the February and today's code, phuhl probably updated his stack or something. Im theorizing that the auto generate command "seems like 'stack init'" pulls from the local stack environment and auto generates a new list of dependencies consistent with the local environment. Hence i think simply autogenerating a new stack file and posting should be sufficient.

**Comment by mitchell-gil96** [comment]
ive already tried nuking stack, and using pacman -Rcns stack to nuke the 30something dependencies it comes with, as well as deleting the $HOME/.stack folder. Then reinstalling stack and trying to run make again from my git cloned folder.

**Comment by MyriaCore** [comment]
Idk. My stuff is able to build usually, but it's honestly kinda difficult to bump this dependency. We might need to do some searching to find an lts that still has all the libraries this thing uses.

They could be fluff too. I might try just nuking some and seeing if it still works.

**Comment by phuhl** [comment]
yeah, for me it sometimes was a pia to get it to build again. I remember deleting the stack directory in the project, in my home folder  uninstalling stack, etc. 

don't know why it is so damn fragile

**Comment by mitchell-gil96** [comment]
Im curious why Haskell was chosen to do this project. I was under the impression that Haskell was more of a math language similar to how R is a statistics language or LaTex an academic one.

If I may ask, how many man-hours did it take to do the bulk of the "logic" of the source code?
Im considering forking this entire thing and re-writing it in C. Ive noticed that the largest use of dependencies seems to be gi-gtk and cairo used for the rendering. The rest such as d-bus, system locale, time can possibly be replaced with similar equivalents in C. Gi-GTK will be the hardest to replace, but ultimately, its just gtk which probably has an equivalent library which can be imported in C with similar functions.

Im thinking C because its the language used for xfce4-notifyd daemon, as well as the gnome version, other rendering tools like picom, lightdm, etc. 

If in the next month or so i come up with a decent draft of this in C, would there be interest in switching the project over whereas to not split man-power between two competing projects? I am proposing this because as you said, haskell is very fragile. I must have counted some 30-50 dependencies required for a single build.

Let me know what you think.

**Comment by MyriaCore** [comment]
IDK, I like the fact that this is written in haskell. It makes it a nice companion to xmonad. It has a very mathey reputaiton, but it tends to produce binaries that are small and performant. Usually tooling isn't awful either, as long as you don't use a ton of random dependencies that aren't really well-maintained. Unfortunately, most of the difficulty here revolves around the fact that a lot of the dependencies aren't really widely used or well maintained at all, so they ended up getting dropped from stackage. 

More power to you if you wanna rewrite this thing in C. I personally hate C, so I couldn't help you.

**Comment by MyriaCore** [comment]
Not gonna lie, I'm not even so sure that all these deps are needed. Like, `hgettext` sounds like it's literally just a way to get text from a specific handle, i.e. stdin, etc. I'm almost *certain* this can be done with something in the stdlib, if it's even being used right now.

**Comment by mitchell-gil96** [comment]
Alot of the dependencies branch from other dependencies. I looked at source and gi-gtk is heavily used throughout, and that has a whole bunch of dependencies listed here:
https://hackage.haskell.org/package/gi-gtk

including my favorite package... gi-pango.
And some of them branch out to even more dependencies. Its a mess of a tree.

As far as WMs go, ive seen on reddit unixporn people using it with awesomeWM (Lua and C), i3wm (C and perl), and it seems phuhl himself uses BSPWM, written almost entirely in C.

I hate C too but it seems to be the go to language for these sort of projects. Maybe re-doing this in C will bring more knowledgeable collaborators. I'll investigate a re-write is feasible and/or even necessary.

**Comment by MyriaCore** [comment]
Most of the gi-* packages in haskell are just autogenerated wrappers for the actual gtk namespaces, so I'm not convinced that this is this big huge dependency, since like 90% of this code is literally just wrapping foreign function calls. 

That being said, I still highly doubt that we need *all* of the packages that are included in stack. If you wanna do a rewrite, that's great, but please open a new issue for that @mitchell-gil96.

**Comment by MyriaCore** [comment]
Looking more seriously at the deps in the cabal file. Quite a few of these are really just foreign function wrappers for native libraries.

- [hgettext](https://hackage.haskell.org/package/hgettext) wraps `libintl.h`
- [setlocale](https://hackage.haskell.org/package/setlocale) wraps CPP's `setlocale`

Just tryna get back on track here:

```
Selected resolver: lts-16.7
Resolver 'lts-16.7' does not have all the packages to match your requirements.
    cairo not found
        - linux-notification-center requires -any
    dbus version 1.2.16 found
        - linux-notification-center requires >=0.10.15 && <1
    gtk3 not found
        - linux-notification-center requires >=0.15.4
    hgettext not found
        - linux-notification-center requires >=0.1.5
    system-locale not found
        - linux-notification-center requires -any
```

Other things we haven't tried:
- gutting some of the weird dependencies, cc @phuhl 
  - what does `gtk3` do that `gi-gtk` and associated libraries doesn't?
  - what does `cairo` do that `gi-cairo` doesn't?
- Can `system-locale` be replaced with something else that's a part of the LTS?
- switching to a nightly instead of an lts
- dropping some of the version caps, for example with `dbus`

As I said before, these problems seem to stem from the fact that many of these packages aren't always in the lts, possibly because they're just not really used often, or because they're not regularly maintained.

**Comment by mitchell-gil96** [comment]
final note on the supposed rewrite, im going to explore feasibility before making any sort of issue.

As far as cabal goes:
system-locale was definitely used for some date functions i forgot in which hs file. Removing it in favor of something native may require a rewrite potentially.

I remember when manually editing the yaml file, dropping version caps produced their own sort of errors that i do not remember at the moment. I think they just outright refused to build unless other deps were up to date. Perhaps removing the max cap and keeping a minimum cap could help.

Im not too sure about switching to nightly, could potentially cause a situation in the future where a bad update breaks everything, and people rush to AUR or issues to complain about broken builds.

I'll investigate src code again but there has to be a reason cairo was listed as one of the five make dependencies.

**Comment by mitchell-gil96** [comment]
After having gone through all the hs files in source, only transparent.hs mentions cairo, and the entirety of that is gi-cairo.

system-locale is called in several files by import System.Locale or import System.Locale.SetLocale

not sure if thats the native version of LTS or if it requires that package

**Comment by MyriaCore** [comment]
It looks like [`gtk3`](https://hackage.haskell.org/package/gtk3) is basically never used. When u look at the depends, it looks like it's in a whole different ecosystem to the gi-style packages. The root namespace is `Graphics.UI`, and that doesn't come up in search. 

[cairo](https://hackage.haskell.org/package/cairo) seems like it is used, but I think we should be able to swap it out for gi-cairo and gi-cairo-render, and rename the imports. At least, that's what appears to happen with [this example project](https://github.com/haskell-gi/haskell-gi/blob/a9832b20fa21294ac0d64b19c1f36eb44f26ab97/cairo/examples/clock/gi-cairo-render-clock.cabal).

More difficult are hgettext and system-locale. we might have to figure out if there's some magic that we can do to basically retrieve those from [hackage](https://hackage.haskell.org) instead of the more curated [stackage](https://www.stackage.org/)

**Comment by phuhl** [comment]
> 
> 
> Im curious why Haskell was chosen to do this project. I was under the impression that Haskell was more of a math language similar to how R is a statistics language or LaTex an academic one.

That is the rep, but the reality is, you can build everything!

> If I may ask, how many man-hours did it take to do the bulk of the "logic" of the source code?

Dunno, not so long. If your are somewhat skilled in haskell, you get quite fast, maybe even faster than in other languages. I chose haskell, because I wrote a REST-API in haskell before. It took me ages to do it, because I was not used to haskell. But I got better. After I finished, I was left with the impression, that the fact, that I was using haskell and it's very unflexible type system led to an API that was basically free of bugs, without writing a single test. Even though, this repo has quite a few issues, lot's of them are due to issues with GTK. The haskell code, in my experience, just works™.

> Im considering forking this entire thing and re-writing it in C. Ive noticed that the largest use of dependencies seems to be gi-gtk and cairo used for the rendering. The rest such as d-bus, system locale, time can possibly be replaced with similar equivalents in C. Gi-GTK will be the hardest to replace, but ultimately, its just gtk which probably has an equivalent library which can be imported in C with similar functions.

That's a lot of work and it is kinda pointless. I would'nt be in for that endavour.

> Im thinking C because its the language used for xfce4-notifyd daemon, as well as the gnome version, other rendering tools like picom, lightdm, etc.

Sure, C ain't a bad choice (maybe, Rust is a better one, nowadays), but Haskell is'nt a bad choice either (except for the lack of devs).

**Comment by phuhl** [comment]
Ah, and Haskell is not fragile, it is the package manager that seems to be. But I just might be using it wrong, too :D

**Comment by phuhl** [comment]
> what does gtk3 do that gi-gtk and associated libraries doesn't?
> what does cairo do that gi-cairo doesn't?

Dunno, was happy to get it running in the first place...

**Comment by phuhl** [comment]
> After having gone through all the hs files in source, only transparent.hs mentions cairo, and the entirety of that is gi-cairo.

Ah right, this was the trick, to enable true transparency, I think

**Comment by MyriaCore** [comment]
For any users stuck with this issue, see #92 for a temporary workaround
