### ISSUE TITLE
Consider using an xml/html library

### ISSUE THREAD

**Issue by MyriaCore** [phuhl/linux_notification_center#93]
Whenever working with tags, the codebase basically parses them with regex. This is usually 'good enough', but it makes the codebase wayyy harder to maintain, since we're basically homebrewing a super limited xml parser whenever we do that. It might be time to consider using a library to parse xml, like [xml](https://www.stackage.org/lts-12.19/package/xml-1.3.14).

This would make adding support for things like body-images much easier (see #27). 

Alternatively, html libraries like [html](https://www.stackage.org/lts-12.19/package/html-1.0.1.2) could help us refactor the regex used in #72 into a nice neat library call. Just food for thought.

**Comment by avdv** [comment]
The only problem with using a xml/html library is that you cannot assume to receive well formed XML / HTML code in general; and you also don't want to reject invalid code but parse on a best effort basis.

That's why I have used tagsoup in my fork to parse the body content and strip unsupported tags from it: https://github.com/avdv/linux_notification_center/commit/e159f32058c05bd48aa7bed52c3b9a4ebced3e20

**Comment by MyriaCore** [comment]
That sounds reasonable. [tagsoup](https://www.stackage.org/lts-12.19/package/tagsoup-0.14.7) doesn't look very difficult to work with either.

**Comment by phuhl** [comment]
Closed by 97f525f958c2f467a2ae52d0fe2c21bbb4197d78
