### ISSUE TITLE
Add support for custom gtk css.

### ISSUE THREAD

**Issue by ahmubashshir** [phuhl/linux_notification_center#97]
It'd be great if we could override the builtin style.css with something like `$XDG_CONFIG_HOME/deadd/style.css`

**Comment by hagen-eriksen** [comment]
Hi there,

I am using this wonderful notification center and so far it has been an incredible experience! It does exactly what I need and I wanted to thank you for this great OSS!

I'm trying to change the CSS of the notification icon but it does not seem to be working.
I followed the instructions on the README:
- Added some CSS to `~/.config/gtk-3.0/gtk.css`:
  ```css
  .deadd-noti-center.notification.icon { margin: 20px; }
  ```
- Restarted `deadd-notification-center` but nothing changed (I also tried some more remarkable changes like changing the titles to red)

Could you provide me with some guidance?

**Comment by ahmubashshir** [comment]
> Hi there,
> 
> I am using this wonderful notification center and so far it has been an incredible experience! It does exactly what I need and I wanted to thank you for this great OSS!
> 
> I'm trying to change the CSS of the notification icon but it does not seem to be working.
> I followed the instructions on the README:
> 
> * Added some CSS to `~/.config/gtk-3.0/gtk.css`:
>   ```css
>   .deadd-noti-center.notification.icon { margin: 20px; }
>   ```
> * Restarted `deadd-notification-center` but nothing changed (I also tried some more remarkable changes like changing the titles to red)
> 
> Could you provide me with some guidance?

I too couldn't... so I'm now directly modifying the css file in code and recompiling it myself.

**Comment by MyriaCore** [comment]
> It'd be great if we could override the builtin style.css with something like `$XDG_CONFIG_HOME/deadd/style.css`

You should already be able to do this, via `~/.config/gtk-3.0/gtk.css`.

> ```css
> .deadd-noti-center.notification.icon { margin: 20px; }
> ```

So, I assume you're trying to change the margins for the **app icon**, correct? The labels for this stuff could be a bit more clear, `icon` is usually used for the app icon, and `image` is usually used for the image to the left of the notification. 

If you *are* trying to modify margins for the app icon, it could be a GTK CSS thing. According to [these docs](https://developer.gnome.org/gtk3/stable/chap-css-properties.html#id-1.5.3.3.29), margin seems to be a gtkbox thing, however I think `.deadd-noti-center.notification.icon` is an image. This doesn't make much sense to me though, since  `.deadd-noti-center.notification.icon` is still the child of a box, so I feel like margin stuff should still apply here. Maybe try with padding instead?

If you're actually trying to modify the **image to the left of the notification**, then you'll want to do it in your `deadd.conf` file. The margins are set in the code here:

https://github.com/phuhl/linux_notification_center/blob/7099d4174f176a8167d78cbad63a65db77bcd75f/src/NotificationCenter/Notifications/AbstractNotification.hs#L77-L85

**Comment by phuhl** [comment]
@MyriaCore 

> If you're actually trying to modify the image to the left of the notification, then you'll want to do it in your deadd.conf file. The margins are set in the code here:

Do you remember, why it was implemented like that? Was it because changing it in the gtk.css wouldn't take effect? In that case, we could remove these config options now, as the CSS configuration allows for changing these margins as desired.

**Comment by phuhl** [comment]
Anyways, this issue is closed due to #118 

For more information, look here: https://github.com/phuhl/linux_notification_center#css-styling
